// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFFlSkKXfZX0b4J7aKplq-7woRWa1Z3g',
    appId: '1:885657811297:web:90dea47cff2150cd0c2d20',
    messagingSenderId: '885657811297',
    projectId: 'stream-heaven-ad95a',
    authDomain: 'stream-heaven-ad95a.firebaseapp.com',
    storageBucket: 'stream-heaven-ad95a.firebasestorage.app',
    measurementId: 'G-8Q6QV4GE8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvNsp6yb17XmcD5doPjJ8rvhzvNZ3k88k',
    appId: '1:885657811297:android:855c24889709a4fc0c2d20',
    messagingSenderId: '885657811297',
    projectId: 'stream-heaven-ad95a',
    storageBucket: 'stream-heaven-ad95a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5CeDwzxQu3C5ySvLJOByPVqHi3QZYaM',
    appId: '1:885657811297:ios:67cd971f933579de0c2d20',
    messagingSenderId: '885657811297',
    projectId: 'stream-heaven-ad95a',
    storageBucket: 'stream-heaven-ad95a.firebasestorage.app',
    iosBundleId: 'com.streamheaven.streamHeavenMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5CeDwzxQu3C5ySvLJOByPVqHi3QZYaM',
    appId: '1:885657811297:ios:67cd971f933579de0c2d20',
    messagingSenderId: '885657811297',
    projectId: 'stream-heaven-ad95a',
    storageBucket: 'stream-heaven-ad95a.firebasestorage.app',
    iosBundleId: 'com.streamheaven.streamHeavenMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFFlSkKXfZX0b4J7aKplq-7woRWa1Z3g',
    appId: '1:885657811297:web:646bae06ec1cabdb0c2d20',
    messagingSenderId: '885657811297',
    projectId: 'stream-heaven-ad95a',
    authDomain: 'stream-heaven-ad95a.firebaseapp.com',
    storageBucket: 'stream-heaven-ad95a.firebasestorage.app',
    measurementId: 'G-LNG61R7CQF',
  );

  /// True when FlutterFire has been configured (no placeholder keys).
  static bool get isConfigured {
    return web.apiKey.isNotEmpty && !web.apiKey.contains('REPLACE');
  }
}
