const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
function w(name, lines) { fs.writeFileSync(path.join(root, name), lines.join("\n"), "utf8"); }
w("scripts/setup-phase1.ps1", [
"# Stream Heaven Phase 1 automated setup (Windows)",
"# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup-phase1.ps1",
"",
"param(",
"  [switch]$SkipInstall,",
"  [switch]$SkipDocker,",
"  [switch]$StartServices,",
"  [switch]$RunSmokeTest",
")",
"",
"$ErrorActionPreference = \"Stop\"",
"$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)",
"Set-Location $RepoRoot",
"",
"function Write-Step([string]$Message) {",
"  Write-Host \"\"",
"  Write-Host (\"==> \" + $Message) -ForegroundColor Cyan",
"}",
"",
"function Test-CommandExists([string]$Name) {",
"  return [bool](Get-Command $Name -ErrorAction SilentlyContinue)",
"}",
"",
"function Invoke-Pnpm([string[]]$PnpmArgs) {",
"  & npx --yes pnpm@9.15.0 @PnpmArgs",
"  if ($LASTEXITCODE -ne 0) { throw (\"pnpm failed: \" + ($PnpmArgs -join \" \")) }",
"}",
"function Copy-EnvFilesIfMissing {",
"  $pairs = @(",
"    @(\"services/auth-service/.env.example\", \"services/auth-service/.env\"),",
"    @(\"services/api-gateway/.env.example\", \"services/api-gateway/.env\"),",
"    @(\"services/user-service/.env.example\", \"services/user-service/.env\"),",
"    @(\"services/realtime-gateway/.env.example\", \"services/realtime-gateway/.env\")",
"  )",
"  foreach ($p in $pairs) {",
"    $src = Join-Path $RepoRoot $p[0]",
"    $dst = Join-Path $RepoRoot $p[1]",
"    if (-not (Test-Path $dst)) {",
"      if (-not (Test-Path $src)) { throw \"Missing example env: $src\" }",
"      Copy-Item $src $dst",
"      Write-Host (\"Created \" + $p[1]) -ForegroundColor Green",
"    } else {",
"      Write-Host (\"Exists: \" + $p[1]) -ForegroundColor DarkGray",
"    }",
"  }",
"}",
"",
"function Wait-DockerHealthy([int]$TimeoutSec = 90) {",
"  $deadline = (Get-Date).AddSeconds($TimeoutSec)",
"  while ((Get-Date) -lt $deadline) {",
"    $psOut = docker compose ps 2>$null",
"    if ($psOut -match \"postgres\" -and $psOut -match \"redis\" -and $psOut -match \"running\") {",
"      Write-Host \"Postgres and Redis are running.\" -ForegroundColor Green",
"      return",
"    }",
"    Start-Sleep -Seconds 3",
"  }",
"  Write-Warning \"Timed out waiting for Docker health; continuing.\"",
"}",
"function Start-DevService([string]$ScriptName, [string]$LogFile) {",
"  $logPath = Join-Path $RepoRoot $LogFile",
"  $logsDir = Split-Path $logPath -Parent",
"  if (-not (Test-Path $logsDir)) { New-Item -ItemType Directory -Path $logsDir | Out-Null }",
"  $cmd = \"Set-Location -LiteralPath '$RepoRoot'; npx --yes pnpm@9.15.0 $ScriptName *>> '$logPath'\"",
"  Start-Process -FilePath \"powershell.exe\" -ArgumentList @(\"-NoProfile\", \"-Command\", $cmd) -WindowStyle Minimized | Out-Null",
"  Write-Host (\"Started \" + $ScriptName + \" -> \" + $LogFile) -ForegroundColor Green",
"}",
"",
"function Wait-HttpOk([string]$Uri, [int]$TimeoutSec = 120) {",
"  $deadline = (Get-Date).AddSeconds($TimeoutSec)",
"  while ((Get-Date) -lt $deadline) {",
"    try {",
"      Invoke-RestMethod -Uri $Uri -Method GET -TimeoutSec 5 | Out-Null",
"      return $true",
"    } catch {",
"      Start-Sleep -Seconds 2",
"    }",
"  }",
"  return $false",
"}",
"",
"Write-Step \"Stream Heaven Phase 1 setup\"",
"Write-Host (\"Repo: \" + $RepoRoot)",
"",
"Write-Step \"Checking node, npm, docker\"",
"if (-not (Test-CommandExists \"node\")) {",
"  throw \"Node.js not found. Install Node 20+ from https://nodejs.org/\"",
"}",
"Write-Host (\"node \" + (node -v))",
"if (-not (Test-CommandExists \"npm\")) { throw \"npm not found\" }",
"Write-Host (\"npm \" + (npm -v))",
"",
"$dockerOk = Test-CommandExists \"docker\"",
"if ($dockerOk) {",
"  Write-Host (docker --version)",
"} else {",
"  Write-Warning \"Docker CLI not found. Install Docker Desktop for Windows and re-run.\"",
"  $SkipDocker = $true",
"}",
"",
"if (-not $SkipInstall) {",
"  Write-Step \"pnpm install (npx pnpm@9.15.0)\"",
"  Invoke-Pnpm @(\"install\")",
"} else {",
"  Write-Host \"Skipped install\" -ForegroundColor Yellow",
"}",
"",
"Write-Step \"Copy .env.example to .env\"",
"Copy-EnvFilesIfMissing",
"",
"if (-not $SkipDocker -and $dockerOk) {",
"  Write-Step \"docker compose up -d postgres redis\"",
"  docker compose up -d postgres redis",
"  if ($LASTEXITCODE -ne 0) { throw \"docker compose up failed\" }",
"  Wait-DockerHealthy",
"  docker compose ps",
"} elseif ($SkipDocker) {",
"  Write-Warning \"Docker skipped. Ensure localhost:5432 and :6379 are available.\"",
"}",
"if ($StartServices) {",
"  Write-Step \"Starting services in background\"",
"  Start-DevService \"dev:auth\" \"logs/dev-auth.log\"",
"  Start-DevService \"dev:user\" \"logs/dev-user.log\"",
"  Start-Sleep -Seconds 3",
"  Start-DevService \"dev:gateway\" \"logs/dev-gateway.log\"",
"  Start-DevService \"dev:realtime\" \"logs/dev-realtime.log\"",
"  Write-Host \"Waiting for http://localhost:3000/health/aggregate ...\"",
"  if (Wait-HttpOk \"http://localhost:3000/health/aggregate\") {",
"    Write-Host \"API gateway healthy\" -ForegroundColor Green",
"  } else {",
"    Write-Warning \"Gateway not ready. See logs/dev-*.log\"",
"  }",
"}",
"",
"Write-Step \"Next steps\"",
"Write-Host @\"",
"",
"If services are not running, use four terminals at repo root:",
"  npx pnpm@9.15.0 dev:auth",
"  npx pnpm@9.15.0 dev:user",
"  npx pnpm@9.15.0 dev:gateway",
"  npx pnpm@9.15.0 dev:realtime",
"",
"Smoke test:",
"  powershell -ExecutionPolicy Bypass -File scripts/smoke-test-phase1.ps1 -AuthLogPath logs/dev-auth.log",
"",
"Or: scripts/setup-phase1.ps1 -StartServices -RunSmokeTest",
"",
"\"@",
"",
"if ($RunSmokeTest) {",
"  Write-Step \"Smoke test\"",
"  $smoke = Join-Path $RepoRoot \"scripts/smoke-test-phase1.ps1\"",
"  $authLog = Join-Path $RepoRoot \"logs/dev-auth.log\"",
"  if (Test-Path $authLog) {",
"    & powershell -ExecutionPolicy Bypass -File $smoke -AuthLogPath $authLog",
"  } else {",
"    & powershell -ExecutionPolicy Bypass -File $smoke",
"  }",
"}",
"",
"Write-Step \"Setup finished\"",
"]);",
console.log("ok");
